# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Weehyerin
tagline:          'ming'
description:      'Hi!!'
url:              https://weehyerin.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed

# Custom vars
version:            3.7.0
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/weehyerin

disqus:
  shortname: Weehyerin

sidebar_link: true